<a href="https://colab.research.google.com/github/pydevforai/Data-Visualization/blob/main/numpytask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Task 1

Create this array:

```
10, 20, 30, 40, 50
```

Find:

- Sum
- Average
- Maximum
- Minimum

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

Sum = np.sum(arr1)
Average = np.mean(arr1)
Max = np.max(arr1)
Min = np.min(arr1)

print(f"Sum: {Sum}")
print(f"Average: {Average}")
print(f"Maximum: {Max}")
print(f"Minimum: {Min}")

Sum: 150
Average: 30.0
Maximum: 50
Minimum: 10


## Task 2

Create this array:

```
45, 80, 30, 90, 55, 20
```

Display only the values greater than or equal to `50`.

In [ ]:
arry = np.array([45, 80, 30, 90, 55, 20])
print(arry[arry >= 50])

[80 90 55]


## Task 3

Create this array:

```
1, 2, 3, 4, 5, 6
```

Change it into:

```
2 rows
3 columns
```

In [ ]:
num = np.array([1, 2, 3, 4, 5, 6])
print(num.reshape(2,3))

[[1 2 3]
 [4 5 6]]


## Task 4

Generate `10` random marks between `40` and `100`.

Then find:

- Average
- Highest marks
- Lowest marks

In [ ]:
marks = np.random.randint(40,100,10)
print(marks)

Avg = np.mean(marks)
Max = np.max(marks)
Min = np.min(marks)

print(f"Average: {Avg}")
print(f"Highest marks: {Max}")
print(f"Lowest marks: {Min}")

[88 81 49 71 76 75 71 55 65 90]
Average: 72.1
Highest marks: 90
Lowest marks: 49


## Task 5

Create this marks array:

```
35, 67, 89, 45, 90, 22, 70, 58
```

Passing marks are `50`.

Find:

- Passed marks
- Failed marks
- Number of passed students
- Number of failed students

In [ ]:
marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])

passed = marks[marks >= 50]
failed = marks[marks < 50]

passed_count = len(passed)
failed_count = len(failed)

print("Passed marks:", passed)
print("Failed marks:", failed)
print("Number of passed students:", passed_count)
print("Number of failed students:", failed_count)


Passed marks: [67 89 90 70 58]
Failed marks: [35 45 22]
Number of passed students: 5
Number of failed students: 3


In [1]:
import numpy as np

# 1. What NumPy is

# NumPy is a Python library used for
# working with arrays and numerical data.

# 2. Creating NumPy arrays

marks = np.array([85, 72, 90, 65, 78])

print("1D Array:")
print(marks)

1D Array:
[85 72 90 65 78]


In [3]:
# 3. 1D and 2D arrays

students = np.array([
    [85, 72, 90],
    [65, 78, 88],
    [92, 81, 75]
])

print("\n2D Array:")
print(students)


2D Array:
[[85 72 90]
 [65 78 88]
 [92 81 75]]


In [4]:
# 4. ndim

print("\nNumber of dimensions:")
print(students.ndim)

# 5. shape

print("\nShape of array:")
print(students.shape)

# 6. size

print("\nTotal number of values:")
print(students.size)


Number of dimensions:
2

Shape of array:
(3, 3)

Total number of values:
9


In [5]:
# 7. dtype

print("\nData type:")
print(students.dtype)

# 8. Indexing

print("\nFirst mark:")
print(marks[0])

print("\nSecond student first subject mark:")
print(students[1][0])

# 9. Slicing

print("\nFirst three marks:")
print(marks[0:3])

print("\nFirst two students:")
print(students[0:2])


Data type:
int64

First mark:
85

Second student first subject mark:
65

First three marks:
[85 72 90]

First two students:
[[85 72 90]
 [65 78 88]]


In [6]:
# 10. Vectorized operations

print("\nMarks + 5:")
print(marks + 5)
print("\nMarks - 5:")
print(marks - 5)
print("\nMarks * 2:")
print(marks * 2)
print("\nMarks / 2:")
print(marks / 2)


Marks + 5:
[90 77 95 70 83]

Marks - 5:
[80 67 85 60 73]

Marks * 2:
[170 144 180 130 156]

Marks / 2:
[42.5 36.  45.  32.5 39. ]


In [7]:
# 11. Mathematical functions
print("\nSquare root:")
print(np.sqrt(marks))

print("\nPower:")
print(np.power(marks, 2))

print("\nAbsolute values:")
numbers = np.array([-10, -5, 5, 10])
print(np.abs(numbers))


Square root:
[9.21954446 8.48528137 9.48683298 8.06225775 8.83176087]

Power:
[7225 5184 8100 4225 6084]

Absolute values:
[10  5  5 10]


In [8]:
# 12. Sum, mean, min and max
print("\nSum:")
print(np.sum(marks))

print("\nMean:")
print(np.mean(marks))

print("\nMinimum:")
print(np.min(marks))

print("\nMaximum:")
print(np.max(marks))


Sum:
390

Mean:
78.0

Minimum:
65

Maximum:
90


In [10]:
# 13. Conditions
print("\nMarks greater than 80:")
print(marks > 80)
print("\nMarks equal to 90:")
print(marks == 90)

# 14. Filtering
print("\nMarks greater than 80:")
print(marks[marks > 80])
print("\nMarks less than 80:")
print(marks[marks < 80])


Marks greater than 80:
[ True False  True False False]

Marks equal to 90:
[False False  True False False]

Marks greater than 80:
[85 90]

Marks less than 80:
[72 65 78]


In [11]:
# 15. Reshape
numbers = np.array([1, 2, 3, 4, 5, 6])
new_array = numbers.reshape(2, 3)
print("\nReshaped Array:")
print(new_array)


Reshaped Array:
[[1 2 3]
 [4 5 6]]


In [12]:
# 16. Flatten
print("\nOriginal 2D Array:")
print(new_array)
flat_array = new_array.flatten()
print("\nFlattened Array:")
print(flat_array)

# 17. Random numbers
random_numbers = np.random.randint(1, 100, 5)
print("\nRandom Numbers:")
print(random_numbers)


Original 2D Array:
[[1 2 3]
 [4 5 6]]

Flattened Array:
[1 2 3 4 5 6]

Random Numbers:
[34 62 76  2 56]
